name: Generate Pacman Graph

on:
  schedule:
    - cron: '0 0 * * *' # roda todo dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Pacman Graph
        uses: AndreRuperto/svg-pacman-contributions@main
        with:
          username: Gabrielly77
          outputDir: output
          commitMessage: "update pacman graph"
